config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/latest'
  post '/rate' => 'rater#create', :as => 'rate'
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, controllers: { registrations: "registrations" }
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/contact'

  resources :products do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'store#index'
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  has_many :line_items
  has_many :reviews
  mount_uploader :avatar, AvatarUploader
  ratyrate_rateable "cost", "durability", "service"

  def self.find_latest_product
    order('created_at DESC').limit(1)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :avatar, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
  <div class="font_family">
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
  <div class= "font_family margin-correct"%>
    <div class="form-group">
      <div class="row">
        <div class ="col-xs-2">
          <%=f.label :title, class: "control-label"%>
        </div>
        <div class="col-xs-6">
          <%=f.text_field :title, placeholder: 'enter title', class: "form-control",required: true%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class ="col-xs-2">
          <%=f.label :description, class: "control-label"%>
        </div>
        <div class="col-xs-6">
          <%=f.text_area :description, placeholder: 'enter description', class: "form-control",
                         required: true%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class ="col-xs-2">
          <%=f.label :price, class: "control-label"%>
        </div>
        <div class="col-xs-2">
          <%=f.text_field :price, placeholder: 'enter price', class: "form-control",
                          required: true%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class="row">
        <div class ="col-xs-2">
          <%=f.label 'upload image', class: "control-label"%>
        </div>
        <div class="col-xs-4">
          <%= f.file_field :avatar, class: "form-control"%>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= f.submit class: "button-create-product"%>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container font_family">
  <div class="row">
    <div class="col-md-12">
      <div class="col-md-3">
        <% @products.each do |product| %>
          <%=link_to product.title, product_path(product) %>
        <% end %>
      </div>
      <div class="col-md-9">
        <div class="caption-full">
          <% @products.each do |product| %>
            <%=image_tag product.avatar.url%>
            Rs:<%=product.price%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
  
  <%if current_user.user_name == 'admin'%> 
    <div class="table-responsive">
      <%= link_to 'New Product', new_product_path %>
    </div>
  <% end %>

app/views/products/new.html.erb
<h1 class ="font_family margin-correct">New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Home page', products_path, class: "button-create-product font_family margin-correct-back" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container font_family">
  <div class="row">
    <div class="col-md-9">
      <div class="caption-full">
          <%=image_tag @product.avatar.url%>
          Rs:<%=@product.price%>
          <div class="ratings">
            cost: <%= rating_for @product, "cost", enable_half: true%>
            durability: <%= rating_for @product, "durability", enable_half: true%>
            service: <%= rating_for @product, "service", enable_half: true%>
          </div>
          <% @product.reviews.each do |review|%>
            <%=review.topic%>
            <%=review.description%>
          <% end %>
            <%=link_to 'Leave a Review', new_product_review_path(@product), remote: true, class: "btn btn-success"%>
          <div id ="new_review"></div>
        </div>
      </div>
    </div>
  </div>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>