config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/latest'
  post '/rate' => 'rater#create', :as => 'rate'
  # devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_for :users, controllers: { registrations: "registrations" }
  resources :line_items
  resources :carts
  get 'store/index'
  get 'store/contact'

  resources :products do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'store#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  has_many :line_items
  has_many :reviews
  mount_uploader :avatar, AvatarUploader
  ratyrate_rateable "cost", "durability", "service"

  def self.find_latest_product
    order('created_at DESC').limit(1)
  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :topic, :description, presence: true
  def self.find_latest
    order('created_at DESC').limit(1)
  end

  def self.find_reviews(product_id)
    where(product_id: product_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # before_action :authenticate_user!
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validate :validate_username
  ratyrate_rater
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:user_name) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
  if User.where(email: user_name).exists?
    errors.add(:user_name, :invalid)
  end
end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController

  def index
    @products  = Product.all
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Online Depot App.</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">De Depot</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav font_family">
            <li class="active"><%=link_to 'Home', root_path%><span class="sr-only">(current)</span></a></li>
            <li><%=link_to 'Offers'%></a></li>
            <li><%=link_to 'products', products_path%></a></li>
            <li><%=link_to 'contact us', store_contact_path%></a></li>
          </ul>
          <form class="navbar-form navbar-left font_family" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            <li class="font_family"><%=link_to 'Cart'%></li>
              <% if !user_signed_in? %>
                <a href="#modalSignin" role="button" class="btn btn-default test-href" data-toggle="modal">
                  <li class="font_family">Sign in/ sign Up</li>
                </a>
              <%end%>
              <div id="modalSignin" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabelSignin" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                      <h3 id="myModalLabelSignin">LOGIN</h3>
                    </div>
                    <div class="modal-body">
                      <%#= form_for(:user, :url => registration_path(:user)) do |f| %>
                      <%=form_for(resource, as: resource_name, url: registration_path(resource_name),
                                  remote: true, html: { id: 'signup_form'} ) do |f| %>
                        <div class="form">
                        <% #if resource.errors.any?%>
                              <%=resource.errors.full_messages %>
                            <% #end %>
                          <div class = "form-register-user"%>
                            <%=f.text_field :email, placeholder: 'email*', required: true%>

                            <%=f.text_field :user_name, placeholder: 'user name*', required: true%>
                            <%=f.password_field :password, placeholder: 'password*', required: true%>
                              <%= f.submit 'create'%>
                            <p class="message-signup">Already registered?<a>Sign In</a></p>
                          </div>
                        </div>
                        <% end-%>
                        <%= form_for(:user, :url => session_path(:user), remote: true,
                                      html: { id: 'login_form' }) do |f| %>
                            <div class="form">
                            <p class="error-message-login">Invalid User name or password</p>
                            <div class = "form-login-user">
                              <%=f.text_field :login, placeholder: 'username or email'%>
                              <%=f.password_field :password, placeholder: 'password'%>
                              <div class="col-md-2">
                                <%= f.check_box :remember_me %>
                              </div>
                              <div class="row">
                                <div class="col-md-6 font_family">
                                  <%= f.label :remember_me %>
                                </div>
                                <div class="dummy_button">
                                   <%= f.submit 'Sign in'%>
                                </div>
                              </div>
                              <p class="message-signin"><a>Not registered?</a></p>
                            </div>
                          </div>
                        <% end %>
                    </div>
                    <div class="modal-footer">
                      <!-- <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                      <button class="btn btn-primary">Save changes</button> -->
                    </div>
                  </div>
                </div>
              </div>
              <%if user_signed_in?%>
                <li ><%=current_user.user_name%></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              <%end%>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </head>
  <body>
    <p class="alert"><%= alert%></p>
    <%= yield %>
  </body>
</html>